[package]
name = "aoc"
version = "0.1.0"
authors = ["Christopher Anderson <chris@nullcode.org>"]
edition = "2018"

[dependencies]
log = "0.4.6"
env_logger = "0.6.0"
failure = "0.1.3"
regex = "1.1.0"
lazy_static = "1.2.0"
